language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

sudo: false
cache:
  - directories:
    - vendor/
